name = "CausalELM"
uuid = "26abab4e-b12e-45db-9809-c199ca6ddca8"
authors = ["Darren Colby <dscolby17@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
